platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
run:
  path: s-c-netflix-ci/tasks/build.sh
inputs:
- name: s-c-netflix-ci
- name: spring-cloud-netflix

caches:
- path: .m2/repository
